# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import audio_streaming_pb2 as audio__streaming__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audio_streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioStreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectParkinsonsFromAudio = channel.stream_unary(
                '/audiostreaming.AudioStreaming/DetectParkinsonsFromAudio',
                request_serializer=audio__streaming__pb2.AudioChunks.SerializeToString,
                response_deserializer=audio__streaming__pb2.ParkinsonsDetectionResult.FromString,
                _registered_method=True)


class AudioStreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectParkinsonsFromAudio(self, request_iterator, context):
        """rpc methods using for this server client interaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectParkinsonsFromAudio': grpc.stream_unary_rpc_method_handler(
                    servicer.DetectParkinsonsFromAudio,
                    request_deserializer=audio__streaming__pb2.AudioChunks.FromString,
                    response_serializer=audio__streaming__pb2.ParkinsonsDetectionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audiostreaming.AudioStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audiostreaming.AudioStreaming', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioStreaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectParkinsonsFromAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/audiostreaming.AudioStreaming/DetectParkinsonsFromAudio',
            audio__streaming__pb2.AudioChunks.SerializeToString,
            audio__streaming__pb2.ParkinsonsDetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
