# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61udio_streaming.proto\x12\x0e\x61udiostreaming\"5\n\x0b\x41udioChunks\x12\x15\n\rrawAudioChunk\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63hunkId\x18\x02 \x01(\x05\"]\n\x19ParkinsonsDetectionResult\x12\x1a\n\x12isHavingParkinsons\x18\x01 \x01(\x08\x12\x10\n\x08severity\x18\x02 \x01(\x02\x12\x12\n\nsuggestion\x18\x03 \x01(\t2w\n\x0e\x41udioStreaming\x12\x65\n\x19\x44\x65tectParkinsonsFromAudio\x12\x1b.audiostreaming.AudioChunks\x1a).audiostreaming.ParkinsonsDetectionResult(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNKS']._serialized_start=41
  _globals['_AUDIOCHUNKS']._serialized_end=94
  _globals['_PARKINSONSDETECTIONRESULT']._serialized_start=96
  _globals['_PARKINSONSDETECTIONRESULT']._serialized_end=189
  _globals['_AUDIOSTREAMING']._serialized_start=191
  _globals['_AUDIOSTREAMING']._serialized_end=310
# @@protoc_insertion_point(module_scope)
